
services:

  principal:
    image: totem-main:latest
    container_name: principal
    expose:
      - "8001"
    env_file:
      - ./totem_main/.env
    restart: unless-stopped

  colegios:
    image: totem-colegios:latest
    container_name: colegios
    expose:
      - "8002"
    env_file:
      - ./totem_colegios_web/.env
    restart: unless-stopped

  vestibulares:
    image: totem-vestibulares:latest
    container_name: vestibulares
    expose:
      - "8003"
    env_file:
      - ./totem_vestibulares_web/.env
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
    depends_on:
      - principal
      - colegios
      - vestibulares
    restart: unless-stopped